### PR TITLE
Party Planner Tab

### PR DESCRIPTION
**Pull request by moorecp**
This is something that I'm not sure if it needs to be in FFRKI or not. My thought is it can provide another feature that can attract more users so we end up collecting more data.

This adds a Party Planner tab to allow the user to try different party combinations with their available characters, abilities, gear, soul breaks, and record materias. It calculates damage as expected based on the provided enemy stats, group buffs, debuffs, and realm synergy. In order for the tab to work, Fiddler has to have seen a response from `/dff/party/list` (just like the Inventory tab).

The UI itself could probably use a lot of work and I'm more than open to suggestions. I'm going ahead and opening the PR to see if there is interest in merging this into the project proper.

The only major outstanding issue I know of is basically all non SSB/BSBs are not yet implemented. It's just a data entry issue at this point and I'll finish that up probably this weekend. It doesn't really impede the use of the feature, though.

There are other things not included like individual buffs and weaker versions of the included buffs (Shout is included, but Flames of War isn't, for instance).

At this point, I'm mostly looking for feedback on whether or not this feature is something people want and, if so, general feedback on things (especially UI suggestions).

### CODE REVIEW

**Comment by KHShadowrunner** [comment]
Myself? I will never say no to new features. I usually hit a wave of fixing something, and getting motivated to do more - but then just falling short and scrapping it all. Tends to be my way. I'll give this a build (I usually do so on another machine, but it's about time I put VS on this thing) and see how it looks and leave feedback - then we should post it to Reddit to see if anyone else has any opinions.

**Comment by KHShadowrunner** [comment]
Visually, I'd like for there to be labels either around the entire character section labeled "Party" or one for each individual party member labeled "Member 1" or something of that like. Seems weird that everything else is labeled and boxed in but those are free-floating so to speak.

We want to put names/labels to the individual dropdowns too (Character / Ability / (damage potential?) / Weapon / Record Materia.

There's a third dropdown under abilities? Is this a unique thing? Perhaps this is for if you have Burst? Dunno - maybe you can help explain it!

We also want to add a note to the top indicating that it will not load until the party menu has been accessed, we can copy/paste this from the other tab if we need to. 

Otherwise - impressive!

**Comment by moorecp** [comment]
As to the third dropdown, that's for selecting a Soul Break to see its damage/healing. There'll be more options there as I get more of that data entered. Right now, it's just SSBs and BSBs.

I honestly feel like there's a significantly different layout that would be clearer/easier to use, etc. I'm just not sure that that is, yet.

**Comment by moorecp** [comment]
I added some more group boxes to organize things a little more along with default text in the combo boxes. I also added a message at the top similar to the one on the inventory tab explaining why the dropdowns might be blank.

**Comment by KHShadowrunner** [comment]
As far as a different layout goes - that's up to feedback, to me it's clear and I like it. I'm not sure what I'd do with it, but that's just me. I bet others are clamoring for some of it in FFRKI.

To try and nitpick more, the character dropdown is a hair to close to the left boundary. And that's it. And that's me trying to find something wrong. 

If you want, post a new thread in reddit to get some other feedback. But screenshot that puppy and see - because it looks fine to me and short of someone saying they dont want it, it looks fine to merge.

**Comment by moorecp** [comment]
You're right. The spacing was off. It should be better, now.

**Comment by moorecp** [comment]
I added a post on reddit to discuss it:

https://www.reddit.com/r/FFRecordKeeper/comments/4fooqy/new_potential_ffrki_feature_party_planner/

**Comment by moorecp** [comment]
All unique soul breaks with damage or healing components have been added.

**Comment by KHShadowrunner** [comment]
This looked like a highly accepted change, and my testing showed nothing break. Let me know when you're good to merge and I'll merge it into master.

**Comment by moorecp** [comment]
I think we're good for a first version. I'm working on somewhat of a redesign to replace the ComboBoxes with a DataGridView that pops up to select equipment. It'll be nice to get feedback on it as it stands then the new version.

**Comment by KHShadowrunner** [comment]
Consider it merged.

**Pull request merged**
